# 端口号
server:
  port: 7401
# 服务名称
spring:
  application:
    name: gateway
# 服务注册与发现相关配置
eureka:
  client:
    # 注册中心地址
    serviceUrl:
      defaultZone: http://peer1:7101/eureka/,http://peer2:7102/eureka/,http://peer3:7103/eureka/
zuul:
  routes:
    api-aaa:
      path: /mv/**
      url:  https://mvnrepository.com/
    api-cons:
      path: /eureka-consumer02/**
      serviceId: eureka-consumer02